<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Seminaire_FISA_A3_servomotor_controller</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
    <PackageReference Include="Vortice.XInput" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="obj\Debug\net10.0-windows\MainWindow.baml" />
  </ItemGroup>

</Project>
